# User Configuration for ${keyboard.name}
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
# Milliseconds of inactivity before entering idle state
CONFIG_ZMK_IDLE_TIMEOUT=20000
# Enable deep sleep support
CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000
